[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[6001]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=opus
auth=6001-auth
aors=6001
transport=transport-udp

[6001-auth]
type=auth
auth_type=userpass
username=6001
password=ChangeMe6001!

[6001]
type=aor
max_contacts=1

[6002]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=opus
auth=6002-auth
aors=6002
transport=transport-udp

[6002-auth]
type=auth
auth_type=userpass
username=6002
password=ChangeMe6002!

[6002]
type=aor
max_contacts=1

[6003]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=opus
auth=6003-auth
aors=6003
transport=transport-udp

[6003-auth]
type=auth
auth_type=userpass
username=6003
password=ChangeMe6003!

[6003]
type=aor
max_contacts=1
